### ISSUE TITLE
Consultation

### ISSUE THREAD

**Issue by joseliko7** [tafayor/SelfCameraShot#1]
Thanks for shared your code ;)

How directly exported a pro version ?

I want to make the app 100 % free.

**Comment by tafayor** [comment]
Go to applyProState in ProHelper.java , and uncomment the line 'isPro = true;'

**Comment by joseliko7** [comment]
Error to export.
Error:(47, 0) Could not find property 'GOOGLE_PLAY_KEY' on BuildType_Decorated{name=release, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, applicationIdSuffix=null, versionNameSuffix=null, minifyEnabled=true, zipAlignEnabled=true, signingConfig=SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[C:\Users\Jose\AppData\Local\Android\sdk\tools\proguard\proguard-android.txt, C:\Users\Jose\Desktop\SelfCameraShot-master\app\proguard-rules.pro], mConsumerProguardFiles=[], mManifestPlaceholders={}}.<a href="openFile:C:\Users\Jose\Desktop\SelfCameraShot-master\app\build.gradle">Open File</a>
Date: Sat, 10 Oct 2015 06:28:25 -0700

**Comment by joseliko7** [comment]
replace 'isPro = true;' for 'isPro = false;' or delete?

**Comment by tafayor** [comment]
You need to add the line GOOGLE_PLAY_KEY=xxxxx  to  gradle.properties; xxxxx  here is the in-app billing key, you can found it in your developer console.
Just uncomment  'isPro = true;'  don't change it.

**Comment by joseliko7** [comment]
I will not charge for the Pro version you understand?




Enviado por Outlook para Android





On Sat, Oct 10, 2015 at 7:47 AM -0700, "Ouadban Youssef" <notifications@github.com> wrote:
You need to add the line GOOGLE_PLAY_KEY=xxxxx  to  gradle.properties; xxxxx  here is the in-app billing key, you can found it in your developer console.
Just uncomment  'isPro = true;'  don't change it.



---

**Comment by tafayor** [comment]
If you uncomment 'isPro = true;' the app will be pro by default, but if you want to cancel the whole pro stuff , search in code and remove everything related to Pro and purchase.
As a start , remove the lines conaining GOOGLE_PLAY_KEY in build.gradle , and the files in 'pro' folder and so on ...

**Comment by joseliko7** [comment]
I want the Pro version pagen me how do I do?

**Comment by tafayor** [comment]
Here is a quick way
1 - In build.gradle  remove the line 'buildConfigField "String", "GOOGLE_PLAY_KEY",  "\"" + GOOGLE_PLAY_KEY + "\""'
2  - In ProConfig.java replace the line 'public static final String GOOGLE_PLAY_KEY = BuildConfig.GOOGLE_PLAY_KEY;'
with  'public static final String GOOGLE_PLAY_KEY = "";'
3- Uncomment 'isPro = true;'

**Comment by joseliko7** [comment]
Thanks! How I can remove the information page ?

**Comment by tafayor** [comment]
If you are an android developer you would know that much.
But note that you should keep the "Legal Notices" page  in app since it contains vendor licenses and credits, and you may change the app name and the owner but you can't change the app license which is GPLv3 and also you have point to the source code of your app as it should be open source.
