### ISSUE TITLE
Help My Please

### ISSUE THREAD

**Issue by joseliko7** [tafayor/SelfCameraShot#1]
I have participated with their code in a contest at my school.
I have not earned money only a good rating and a trophy.

My teacher has found that its application is equal to mine.

Can you talk to my teacher and tell the code I 've created?
I have not created the code of self camera shot.

I feel bad to ask this.
Could you tell my teacher that I created the code?

I will solve life, I get my graduation.

**Comment by tafayor** [comment]
You took my code and told your teacher that it's yours and you want me to confirm it to your teacher !! That prize should be mine not yours.

**Comment by joseliko7** [comment]
I understand.
I understand that there should be no echo that.
And I ask forgiveness of heart.

But please I beg you to help me.
At the end of the day sooner or later once adopted will give you all the credits.

**Comment by joseliko7** [comment]
Can you create within your web a hidden page indicating that I echo the code from scratch?
I beg you to its knees.

example:

http://tafayor.com/Attribution2
